package com.napier.sem;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;

/**
 * Class to deal with reports relating to capital cities.
 * Contains methods to query capital cities by continent, region, or in the world.
 * Contains a display method to directly output contents of report.
 */
public class CapitalCityReport {

    private Connection con;
    private ArrayList<City> cities = new ArrayList<>();

    public CapitalCityReport(Connection con) {
        this.con = con;
    }

    /**
     * Processes results from a resultset generated by an SQL query
     * Adds each individual city processed to this report's list of cities
     * @param rslt ResultSet to process
     * @throws SQLException
     */
    private void processResults(ResultSet rslt) throws SQLException {
        while (rslt.next()) {
            City city = new City();
            city.id = rslt.getInt("ID");
            city.name = rslt.getString("Name");
            city.countryCode = rslt.getString("CountryCode");
            city.district = rslt.getString("District");
            city.population = rslt.getInt("Population");
            cities.add(city);
        }
    }

    /**
     * Retrieves all capital cities in the world, ordered by population from largest to smallest.
     * Adds each capital city to this report's list of cities.
     * @param limit the maximum number of results to return. Use -1 to return all capital cities.
     */
    public void getPopulousCapitalCitiesInWorld(int limit) {
        try {
            Statement stmt = con.createStatement();
            String sql = "SELECT city.ID, city.Name, city.CountryCode, city.District, city.Population " +
                    "FROM city " +
                    "JOIN country ON country.Code = city.CountryCode " +
                    "WHERE city.ID = country.Capital "+
                    "ORDER BY city.Population DESC";
            if (limit != -1) {
                sql += " LIMIT " + limit;
            }
            ResultSet resultSet = stmt.executeQuery(sql);
            processResults(resultSet);
        } catch (Exception e) {
            System.out.println(e.getMessage());
            System.out.println("Failed to access capital cities");
        }
    }


    /**
     * Retrieves all capital cities within the specified continent, ordered by population from largest to smallest.
     * Adds each capital city to this report's list of cities.
     * @param continent the name of the continent (e.g., "Asia")
     * @param limit the maximum number of results to return. Use -1 to return all matching capital cities.
     */
    public void getPopulousCapitalCitiesFromContinent(String continent, int limit) {
        try {
            Statement stmt = con.createStatement();
            String sql = "SELECT city.ID, city.Name, city.CountryCode, city.District, city.Population " +
                    "FROM city " +
                    "JOIN country ON country.Code = city.CountryCode " +
                    "WHERE city.ID = country.Capital AND country.Continent = '" + continent + "' " +
                    "ORDER BY city.Population DESC";
            if (limit != -1) {
                sql += " LIMIT " + limit;
            }
            ResultSet resultSet = stmt.executeQuery(sql);
            processResults(resultSet);
        } catch (Exception e) {
            System.out.println(e.getMessage());
            System.out.println("Failed to identify continent");
        }
    }


    /**
     * Retrieves all capital cities within the specified region, ordered by population from largest to smallest.
     * Adds each capital city to this report's list of cities.
     * @param region the name of the region (e.g., "Caribbean")
     * @param limit the maximum number of results to return. Use -1 to return all matching capital cities.
     */
    public void getPopulousCapitalCitiesFromRegion(String region, int limit) {
        try {
            Statement stmt = con.createStatement();
            String sql = "SELECT city.ID, city.Name, city.CountryCode, city.District, city.Population " +
                    "FROM city " +
                    "JOIN country ON country.Code = city.CountryCode " +
                    "WHERE city.ID = country.Capital AND country.Region = '" + region + "' " +
                    "ORDER BY city.Population DESC";
            if (limit != -1) {
                sql += " LIMIT " + limit;
            }
            ResultSet resultSet = stmt.executeQuery(sql);
            processResults(resultSet);
        } catch (Exception e) {
            System.out.println(e.getMessage());
            System.out.println("Failed to identify region");
        }
    }


    /**
     * Display method for cities in this report
     */
    public void displayReport() {
        if (cities.isEmpty()) {
            System.out.println("There are no cities in this report.");
        }
        else {
            for (City city : cities) {
                System.out.println(city.id + " | " +
                        city.name + " | " +
                        city.countryCode + " | " +
                        city.population);
            }
        }
    }
}
