package com.napier.sem;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;

public class CityReport {

    private Connection con;
    private ArrayList<City> cities = new ArrayList<>();

    public CityReport(Connection con) {
        this.con = con;
    }

    /**
     * Processes results from a resultset generated by an SQL query
     * Adds each individual city processed to this report's list of cities
     * @param rslt ResultSet to process
     * @throws SQLException
     */
    private void processResults(ResultSet rslt) throws SQLException {
        while (rslt.next()) {
            City city = new City();
            city.id = rslt.getInt("ID");
            city.name = rslt.getString("Name");
            city.countryCode = rslt.getString("CountryCode");
            city.district = rslt.getString("District");
            city.population = rslt.getInt("Population");
            cities.add(city);
        }
    }

    /**
     * Method to search database for details of city by provided ID
     * Will add City to this report's list of cities
     * @param id the Alpha-3 code of the required country
     */
    public void getCityFromID(int id) {
        try {
            Statement stmt = con.createStatement();
            String sql = "SELECT ID, Name, CountryCode, District, Population " +
                    "FROM city " +
                    "WHERE ID = " + id;
            ResultSet resultSet = stmt.executeQuery(sql);
            processResults(resultSet);
        }
        catch (Exception e) {
            System.out.println(e.getMessage());
            System.out.println("Failed to get city");
        }
    }

    /**
     * Method to search database for the most populated cities in the world
     * Will add City to this report's list of cities
     * @param limit the number of Countries. -1 for all
     */
    public void getPopulousCitiesInWorld(int limit) {
        try {
            Statement stmt = con.createStatement();
            String sql = "SELECT ID, Name, CountryCode, District, Population " +
                    "FROM city " +
                    "ORDER BY Population DESC";
            if (limit != -1) {
                sql += " LIMIT " + limit;
            }
            ResultSet resultSet = stmt.executeQuery(sql);
            processResults(resultSet);
        }
        catch (Exception e) {
            System.out.println(e.getMessage());
            System.out.println("Failed to access cities");
        }
    }


    /**
     * Method to search database for the most populated cities of a specified continent
     * Will add City to this report's list of cities
     * @param continent the continent the cities should be in
     * @param limit the number of Cities. -1 for all
     */
    public void getPopulousCitiesFromContinent(String continent, int limit) {
        try {
            Statement stmt = con.createStatement();
            String sql = "SELECT ID, Name, CountryCode, District, Population " +
                    "FROM city " +
                    "JOIN country ON country.Code = city.CountryCode " +
                    "WHERE country.Continent = '" + continent + "' " +
                    "ORDER BY Population DESC";
            if (limit != -1) {
                sql += " LIMIT " + limit;
            }
            ResultSet resultSet = stmt.executeQuery(sql);
            processResults(resultSet);
        }
        catch (Exception e) {
            System.out.println(e.getMessage());
            System.out.println("Failed to identify country");
        }
    }


    /**
     * Method to search database for the most populated cities of a specified region
     * Will add City to this report's list of cities
     * @param region the region cities should be in
     * @param limit the number of Cities. -1 for all
     */
    public void getPopulousCitiesFromRegion(String region, int limit) {
        try {
            Statement stmt = con.createStatement();
            String sql = "SELECT city.ID, city.Name, city.CountryCode, city.District, city.Population " +
                    "FROM city " +
                    "JOIN country ON country.Code = city.CountryCode " +
                    "WHERE country.Region = '" + region + "' " +
                    "ORDER BY city.Population DESC";
            if (limit != -1) {
                sql += " LIMIT " + limit;
            }
            ResultSet resultSet = stmt.executeQuery(sql);
            processResults(resultSet);
        }
        catch (Exception e) {
            System.out.println(e.getMessage());
            System.out.println("Failed to identify country");
        }
    }

    /**
     * Method to search database for the most populated cities of a specified country
     * Will add City to this report's list of cities
     * @param countryCode the countrycode of the country cities should be in
     * @param limit the number of Cities. -1 for all
     */
    public void getPopulousCitiesFromCountry(String countryCode, int limit) {
        try {
            Statement stmt = con.createStatement();
            String sql = "SELECT ID, Name, CountryCode, District, Population " +
                    "FROM city " +
                    "WHERE CountryCode = '" + countryCode + "' " +
                    "ORDER BY Population DESC";
            if (limit != -1) {
                sql += " LIMIT " + limit;
            }
            ResultSet resultSet = stmt.executeQuery(sql);
            processResults(resultSet);
        }
        catch (Exception e) {
            System.out.println(e.getMessage());
            System.out.println("Failed to identify country");
        }
    }

    /**
     * Method to search database for the most populated cities of a specified district
     * Will add City to this report's list of cities
     * @param district the district cities should be in
     * @param limit the number of Cities. -1 for all
     */
    public void getPopulousCitiesFromDistrict(String district, int limit) {
        try {
            Statement stmt = con.createStatement();
            String sql = "SELECT ID, Name, CountryCode, District, Population " +
                    "FROM city " +
                    "WHERE District = '" + district + "' " +
                    "ORDER BY Population DESC";
            if (limit != -1) {
                sql += " LIMIT " + limit;
            }
            ResultSet resultSet = stmt.executeQuery(sql);
            processResults(resultSet);
        }
        catch (Exception e) {
            System.out.println(e.getMessage());
            System.out.println("Failed to identify country");
        }
    }

    /**
     * Display method for cities in this report
     */
    public void displayReport() {
        if (cities.isEmpty()) {
            System.out.println("There are no cities in this report.");
        }
        else {
            for (City city : cities) {
                System.out.println(city.name + " | " +
                        city.countryCode + " | " +
                        city.district + " | " +
                        city.population);
            }
        }
    }
}
