package com.napier.sem;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;

/**
 * Class to deal with reports relating to population.
 * Contains methods to query urban and non-urban population breakdown of countries within a Continent, Region or in the world.
 * Contains a display method to directly output contents of report.
 */
public class PopulationReport {

    private Connection con;
    private ArrayList<Population> pops = new ArrayList<>();

    public PopulationReport(Connection con) {
        this.con = con;
    }

    /**
     * Processes results from a resultset generated by an SQL query
     * Adds each population generated by query to this report's list of populations
     * @param rslt ResultSet to process
     * @throws SQLException
     */
    private void processCountryResults(ResultSet rslt) throws SQLException {
        while (rslt.next()) {
            Population pop  = new Population();
            pop.countryName = rslt.getString("name");
            pop.population = rslt.getInt("total pop");
            pops.add(pop);
        }
    }

    /**
     * Processes results from a resultset generated by an SQL query
     * Adds the comparison of urban vs rural population to each pre-existing population in this report
     * @param rslt ResultSet to process
     * @throws SQLException
     */
    private void processUrbanResults(ResultSet rslt) throws SQLException {
        int i = 0;
        while (rslt.next()) {
            Population pop = pops.get(i);
            pop.urbanPop = rslt.getDouble("urban pop");
            double urbanPercentage = (pop.urbanPop * 100.0f /pop.population);
            pop.urbanPercent  = String.format("%.2f", urbanPercentage);
            pop.ruralPop = pop.population - pop.urbanPop;
            double ruralPercentage = (pop.ruralPop * 100.0f /pop.population);
            pop.ruralPercent = String.format("%.2f", ruralPercentage);
            i++;

        }
    }

    /**
     * Method to search database for urban and rural population breakup of countries in a specified continent
     * Will add Population to this reports list of Populations
     * @param continent the continent to show population of countries in
     */
    public void getPopulationsFromContinent(String continent) {
        try {
            Statement stmt = con.createStatement();
            String sql = "SELECT Name, SUM(country.Population) AS 'total pop'" +
                        "FROM country " +
                        "WHERE continent = '" + continent + "' " +
                        "GROUP BY Code";
            ResultSet resultSet = stmt.executeQuery(sql);
            processCountryResults(resultSet);

            stmt = con.createStatement();
            sql = "SELECT SUM(city.Population) AS 'urban pop' " +
                    "FROM city " +
                    "JOIN country ON country.Code = city.CountryCode " +
                    "WHERE country.Continent = '" + continent + "' " +
                    "GROUP BY country.Code";
            resultSet = stmt.executeQuery(sql);
            processUrbanResults(resultSet);

        }
        catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }

    /**
     * Method to search database for urban and rural population breakup of countries in a specified region
     * Will add Population to this reports list of Populations
     * @param region the region to show population of countries in
     */
    public void getPopulationsFromRegion(String region) {
        try {
            Statement stmt = con.createStatement();
            String sql = "SELECT Name, SUM(country.Population) AS 'total pop'" +
                    "FROM country " +
                    "WHERE Region = '" + region + "' " +
                    "GROUP BY Code";
            ResultSet resultSet = stmt.executeQuery(sql);
            processCountryResults(resultSet);

            stmt = con.createStatement();
            sql = "SELECT SUM(city.Population) AS 'urban pop' " +
                    "FROM city " +
                    "JOIN country ON country.Code = city.CountryCode " +
                    "WHERE country.Region = '" + region + "' " +
                    "GROUP BY country.Code";
            resultSet = stmt.executeQuery(sql);
            processUrbanResults(resultSet);

        }
        catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }

    /**
     * Method to search database for urban and rural population breakup of every country in the world
     * Will add Population to this reports list of Populations
     */
    public void getPopulationsFromCountry() {
        try {
            Statement stmt = con.createStatement();
            String sql = "SELECT Name, SUM(country.Population) AS 'total pop'" +
                    "FROM country " +
                    "GROUP BY Code";
            ResultSet resultSet = stmt.executeQuery(sql);
            processCountryResults(resultSet);

            stmt = con.createStatement();
            sql = "SELECT SUM(city.Population) AS 'urban pop' " +
                    "FROM city " +
                    "JOIN country ON country.Code = city.CountryCode " +
                    "GROUP BY country.Code";
            resultSet = stmt.executeQuery(sql);
            processUrbanResults(resultSet);

        }
        catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }


    /**
     * Display method for countries in this report
     */
    public void displayReport() {
        if (pops.isEmpty()) {
            System.out.println("There are no populations in this report.");
        }
        else {
            for (Population pop : pops) {
                if (pop == null) {
                    continue;
                }
                System.out.println(pop.countryName + " | " +
                                    pop.population + " | " +
                                    pop.urbanPop + " ("+ pop.urbanPercent + ") | " +
                                    pop.ruralPop + " ("+ pop.ruralPercent + ")");
            }
        }
    }

    public ArrayList<Population> getPopulations() {
        return pops;
    }

    public void addCountry(Population pop) {
        pops.add(pop);
    }
}
